name: smart_cloud
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  logging: ^1.3.0
  fl_chart: ^0.63.0  # Adding fl_chart dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
